#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libfixmath
Version  : 1416c9979635c69f344d3c1de84b3246001a6540
Release  : 1
URL      : https://github.com/PetteriAimonen/libfixmath/archive/1416c99/libfixmath-1416c9979635c69f344d3c1de84b3246001a6540.tar.gz
Source0  : https://github.com/PetteriAimonen/libfixmath/archive/1416c99/libfixmath-1416c9979635c69f344d3c1de84b3246001a6540.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libfixmath-license = %{version}-%{release}
BuildRequires : buildreq-cmake
Patch1: 0001-Enable-installation.patch

%description
# libfixmath
This is a mirror of the libfixmath's original SVN repository on Google Code.

%package dev
Summary: dev components for the libfixmath package.
Group: Development
Provides: libfixmath-devel = %{version}-%{release}
Requires: libfixmath = %{version}-%{release}

%description dev
dev components for the libfixmath package.


%package license
Summary: license components for the libfixmath package.
Group: Default

%description license
license components for the libfixmath package.


%package staticdev
Summary: staticdev components for the libfixmath package.
Group: Default
Requires: libfixmath-dev = %{version}-%{release}

%description staticdev
staticdev components for the libfixmath package.


%prep
%setup -q -n libfixmath-1416c9979635c69f344d3c1de84b3246001a6540
cd %{_builddir}/libfixmath-1416c9979635c69f344d3c1de84b3246001a6540
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666821457
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1666821457
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libfixmath
cp %{_builddir}/libfixmath-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libfixmath/dc23713e45a9d0da198d71e7da484a47d99f7760
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libfixmath/fix16.h
/usr/include/libfixmath/fix16.hpp
/usr/include/libfixmath/fix16_trig_sin_lut.h
/usr/include/libfixmath/fixmath.h
/usr/include/libfixmath/fract32.h
/usr/include/libfixmath/int64.h
/usr/include/libfixmath/uint32.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libfixmath/dc23713e45a9d0da198d71e7da484a47d99f7760

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/liblibfixmath.a
